### PR TITLE
Add logfile attribute

### PR DESCRIPTION
**Pull request by aaron-lane**
This branch adds the feature of specifying a logfile path in ntp.conf.

### CODE REVIEW

**Comment by gmiranda23** [comment]
Merged #101.  But I'm waiting until the new work week for release so we don't screw up anyone's weekend.

**Comment by shortdudey123** [comment]
attribute is not documented.  Add it to the readme?

**Comment by aaron-lane** [comment]
@shortdudey123 @gmiranda23 I didn't know if it should be added to the README because the sections only refer to "suggested" and "platform" attributes.

**Comment by shortdudey123** [comment]
fair point, up to @gmiranda23

**Comment by aaron-lane** [comment]
@gmiranda23 is 1.8.4 going to be released this week?

**Pull request closed without merging**
