### PR TITLE
Fix for apparmor issue https://github.com/gmiranda23/ntp/issues/103

### PR DESCRIPTION
**Pull request by pkringle**
Here is only fix I have found for the problem I described in 
https://github.com/gmiranda23/ntp/issues/103

Thanks

### CODE REVIEW

**Comment by TD-4242** [comment]
I get my logs and dmesg spamed by this as well.  would it be possible to merge this minor change?

**Comment by jperville** [comment]
+1

**Comment by jperville** [comment]
Hi @pkringle , could you update your PR to grant ntpd access `/opt/chef/embedded/bin` in addition to `/usr/local/bin` and `/usr/local/sbin`? As mentionned in #103, ntpd seems to scan every entry in `$PATH`, and the chef omnibus path is likely to be included if running chef-client.

**Comment by ikurochkin** [comment]
:+1: having the same problem

**Comment by iserko** [comment]
same here

it'd be great to find a generic solution that will fix it for all paths in `PATH`

but until then :+1: for this PR

**Comment by lfrodrigues** [comment]
Please merge this, currently I'm running from my own forked repo with this patch

**Comment by tas50** [comment]
#124 was merged in which should fix this issue.  Open an issue up if it's still a problem and I'll track it down.

**Pull request closed without merging**
